### ISSUE TITLE
Selection by AA

### ISSUE THREAD

**Issue by Sanrrone** [Lattice-Automation/seqviz#100]
Hi JJ,
I was playing with seqViz again and I notice when you click the aminoacid, the selection wrap the whole sequence. Is there a way to select only the codon you clicked based on the aminoacid?. 
I was playing with the `la-vz-linear-translations` class but I cannot track the id for each AA (they are dynamically generated).

if is not possible, Is there a way to set a selection? I mean, like an imaginary option called setSelection: {start: 0, end: 10} in case you want to select the first 10 nucleotides. Is there a way to trigger this kind of selection?

thanks you very much in advance,
Sandro

**Comment by Sanrrone** [comment]
Hi,
I found the onSelection attr start and end can handle the visualization. So forget my issue.

**Comment by Sanrrone** [comment]
Anyway, is there a way to make the selection by clicking the aminocid?

thanks!

**Comment by jjti** [comment]
what do you think about a double click, where clicking an AA once would select that AA and twice would select the full translation? Kind of like how double click on text in a browser select one word, and triple click selects the full sentence?

**Comment by Sanrrone** [comment]
It would be perfect!.
Taking advantage of this reply, I'm wondering if is possible to add the nucleotide index in both sides of the sequence? or put them before the annotations?, this is because when I have many annotations flags the ticks down so much and I cannot check easly the position of my selection. I was thinking in a new option like `dnaRange: "both" #top, bottom, both`. But, if the index is before the annotations would be ok for me.

thanks you in advance!

**Comment by jjti** [comment]
Hey I just added this in last commit: https://github.com/Lattice-Automation/seqviz/commit/98a3eb43c98641d21d4e693690cba54db02f0750

Should be in there for version `3.0.42` and higher. Let me know if you have any issues w/ it

With regards to the index position (both sides) lets move to another issue if that's alright :)
