### ISSUE TITLE
Search algorithm broken with mismatches

### ISSUE THREAD

**Issue by zeroaltitude** [Lattice-Automation/seqviz#102]
There's a minor, but real, bug in search.js.

For exact matches, the code uses a regex with gi -- this explicitly means one is allowed to search case-insensitively. In addition, it does not place any restrictions on the alphabet you use. It's unclear to me whether there's a secondary bug relating to the fact that I'm not sure the code is handling wildcards here.

But for mismatches, the code is absolutely handling wildcards. Unfortunately, the code also tightly restricts the algorithm to the alphabet used, and worse, it doesn't accept case-insensitive matches. The result is that if one uses all caps DNA sequences, the mismatch-allowing search returns every possible substring as a match.

This is incorrect. My plan is to fork, fix this issue, and submit it as a pull request.

Thanks for your attention!

**Comment by zeroaltitude** [comment]
PR submitted: https://github.com/Lattice-Automation/seqviz/pull/103

**Comment by jjti** [comment]
Ay that's a big catch, thanks. I'm surprised that wasn't caught before now. Thanks for fixing and adding some tests for the fix (something I've been lazy about lately). I merged and pushed the patch in v3.0.37

**Comment by zeroaltitude** [comment]
Thanks! This is great!
