### ISSUE TITLE
Handle overlapping enzyme labels on the Linear Viewer

### ISSUE THREAD

**Issue by nicolazilio** [Lattice-Automation/seqviz#104]
Hi there,

I just wanted to let you know that when two restriction enzyme sites are very close to each other, the labels overlap. Would it be possible to shift one of the labels on a different "level" so that they don't overlap anymore?

Thank you!

Nicola

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/2800360/118821184-4751c800-b8b7-11eb-97b3-946e0104625f.png)

**Comment by jjti** [comment]
Yes this should be possible to fix. It's a bit tricky to get the text to not overlap, but definitely possible/should happen

**Comment by sahasukanta** [comment]
Hi! I was just wondering on the status of this issue? Is a fix in progress or its gotten stale?

**Comment by jjti** [comment]
It's super stale @sahasukanta. Thank you for bumping/reminding me though. I'll try to get this done within the next month

**Comment by jjti** [comment]
@sahasukanta can you check out the change in the latest patch and let me know what you think? https://github.com/Lattice-Automation/seqviz/releases/tag/3.7.4

It's not perfect or really that smart, it just moves the righter-most enzyme label to the right on overlap. It's not quite like the circular viewer where overlapping labels are grouped, and shown on hover. Also, if the righter-most label gets pushed off the screen to the right, it's removed.

On a more positive note, hovering a cut-site now highlights the recognition site + darkens the enzyme name which I hope improves the experience a bit. 

<img width="410" alt="Screen Shot 2023-01-07 at 1 41 46 PM" src="https://user-images.githubusercontent.com/13923102/211166084-52f40f87-b5c6-4767-868e-f9625a9488c9.png">

**Comment by sahasukanta** [comment]
> @sahasukanta can you check out the change in the latest patch and let me know what you think? https://github.com/Lattice-Automation/seqviz/releases/tag/3.7.4
> 
> It's not perfect or really that smart, it just moves the righter-most enzyme label to the right on overlap. It's not quite like the circular viewer where overlapping labels are grouped, and shown on hover. Also, if the righter-most label gets pushed off the screen to the right, it's removed.
> 
> On a more positive note, hovering a cut-site now highlights the recognition site + darkens the enzyme name which I hope improves the experience a bit.
> 
> <img alt="Screen Shot 2023-01-07 at 1 41 46 PM" width="410" src="https://user-images.githubusercontent.com/13923102/211166084-52f40f87-b5c6-4767-868e-f9625a9488c9.png">

@jjtimmons I just tried the new release and it looks like there is an issue with the name position relative to the actual site on the map. The name sometimes seems to be at the next site instead of on the site itself. But the highlight on hover is working great!

![Screenshot (682)](https://user-images.githubusercontent.com/67036234/211170138-783b7b65-15f4-470d-b8c3-0420179e5e9f.png)
![Screenshot (681)](https://user-images.githubusercontent.com/67036234/211170143-09046732-3d25-42bf-ad39-6b7d930d7ca3.png)
![Screenshot (683)](https://user-images.githubusercontent.com/67036234/211170187-1f8bf36a-7106-41d5-ad7c-45cfa6121886.png)

**Comment by jjti** [comment]
Hey @sahasukanta , thanks a ton for the quick test and feedback re: enzyme labels. I believe I fixed the issue in the latest patch, before/after screenshot included using your example: https://github.com/Lattice-Automation/seqviz/releases/tag/3.7.5

If you don't mind, please let me know how it works

**Comment by sahasukanta** [comment]
> Hey @sahasukanta , thanks a ton for the quick test and feedback re: enzyme labels. I believe I fixed the issue in the latest patch, before/after screenshot included using your example: https://github.com/Lattice-Automation/seqviz/releases/tag/3.7.5
> 
> If you don't mind, please let me know how it works

Hi @jjtimmons . These changes look great! Thanks a lot for the quick fixes too :D

**Comment by jjti** [comment]
Awesome and thanks @sahasukanta , closing now
