### ISSUE TITLE
Zoom issues

### ISSUE THREAD

**Issue by guzmanvig** [Lattice-Automation/seqviz#107]
If translations are being drawn (options.translations), zooming in or out duplicate them. Refreshing the page removes the duplicates.

Also, zooming in or out the circle view doesn't seem to work.

**Comment by jjti** [comment]
> zooming in or out the circle view doesn't seem to work.

this should rotate the viewer (unless `rotateOnScroll = false`). It might be a bug tbh? but I can't replicate
