### ISSUE TITLE
Demo updates

### ISSUE THREAD

**Issue by guzmanvig** [Lattice-Automation/seqviz#108]
I think that the demo webpage (https://tools.latticeautomation.com/seqviz/) is using an outdated version of the code. This is because the search functionality is not working and the request to get the part uses a proxy (which was removed in the latest version).

Also, a couple of small updates to the README could be made: 
- value 0 for directionality property in annotations which removes the arrow from both ends is not mentioned
-  color property in annotations which changes the color of it, is also not mentioned.

Thanks!

**Comment by jjti** [comment]
Someone with AWS creds needs to run `npm run demo`

I updated the README to me more explicit about direction undefined or == 0: https://github.com/Lattice-Automation/seqviz/commit/40e306fcf72b12f077a00e2fe59438c0089267cd

The color update to README was addressed in commit for the other (now closed) issue

**Comment by jjti** [comment]
I ejected from CRA for the sake of the Typescript conversion and now [craco](https://github.com/dilanx/craco) (a diff framework we're using for the demo) is totally unusable. The demo part of things will need to be rewritten or migrated to a diff tool or something

I'm leaning towards Storybook: https://storybook.js.org/docs/react/get-started/introduction

**Comment by jjti** [comment]
This is done. Huge PITA, involved moving from Craco to Next.js. Anyone with Lattice creds in a profile called `lattice` can update
