### ISSUE TITLE
React Error - Duplicate Keys

### ISSUE THREAD

**Issue by martin-simonsen-raven** [Lattice-Automation/seqviz#109]
When using the SeqViz React component in an app where the sequence and annotations can be changed dynamically, the SeqViz component will often cause the following error:

_"Warning: Encountered two children with the same key, `5829780135-0`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version."_

The error occurs randomly but is easy to reproduce.

The rendering of annotations will be scrambled when this error occurs and it seems to be related to a corrupt component state. Reloading the page will solve the problem. I've implemented a workaround where the parent component will first render the page without the SeqViz component and after a delay of 100ms the page is rendered again with the SeqViz component to force a reset of the state.

**Comment by jjti** [comment]
I remember seeing this awhile ago but I cannot replicate it. Either I'm missing the trigger or it was fixed in some other recent fix. Do you mind using the latest version and letting me know if/when you see it?

**Comment by martin-simonsen-raven** [comment]
I'll see if I can produce a minimal example using the newest library when time allows it.

**Comment by martin-simonsen-raven** [comment]
Upgrading from 3.0.38 to 3.0.42 seems to have fixed the problem. Thanks for maintaining this package.

**Comment by jjti** [comment]
Awesome! Glad to hear and thanks for checking. I appreciate it
