### ISSUE TITLE
Regenerator runtime in the README.md file

### ISSUE THREAD

**Issue by isaacguerreir** [Lattice-Automation/seqviz#110]
So, I think will be interesting to put in the README.md file, in the Installation section, about using SeqViz through CDN, the use of the regenerator-runtime library, like this:

`<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/regenerator-runtime@0.13.3/runtime.min.js"></script>
    <script type="text/javascript" src="https://unpkg.com/seqviz"></script>`

Without the regenerator-runtime SeqViz doesn't work directly.

**Comment by jjti** [comment]
Awesome and thanks. Didn't think of this. Just updated/patched the README with that
