### ISSUE TITLE
SeqViz componentDidUpdate logic rework

### ISSUE THREAD

**Issue by crudnicky** [Lattice-Automation/seqviz#112]
I have discovered an edge case that is triggered when changing the viewer state. I noticed in my application that despite sending the correct props to SeqViz, certain plasmid maps were rendering the incorrect start and stop indexes for the annotations. I found that this was due to incoming annotations using the previous plasmid's sequence length in the `parseAnnotations()` function (`SeqViz.jsx` line 138).  In the `componentDidUpdate()` hook, when the previous props are destructed, the sequence length of the previous plasmid is extracted. This value is then passed into the `parseAnnotations()`function with **the current annotations**. I believe that the **current sequence** should be used instead of the prior sequence so that an accurate calculation of the annotation start / stop index can be made.

I have cloned a local copy of seqviz and used `npm link` to generate a symlink between the local seqviz and my application. When I change line `SeqViz.jsx` line 138 from

`this.setState({ annotations: this.parseAnnotations(this.props.annotations, seq) });`

to 

`this.setState({ annotations: this.parseAnnotations(this.props.annotations, this.props.seq) });`

My plasmid maps render correctly.

**Comment by jjti** [comment]
You're awesome and thanks for catching this. I just pushed a fix for this in `3.0.40`. 

https://github.com/Lattice-Automation/seqviz/commit/20f7866a8e322f80ecf285031731ed0ed5152f6c
