### ISSUE TITLE
seqviz

### ISSUE THREAD

**Issue by vpandey-om** [Lattice-Automation/seqviz#114]
Hi,

I am using seqviz and it seems very cool. 

I am getting error: Uncaught TypeError: Cannot read properties of undefined (reading 'Viewer')

<script type="text/javascript" src="https://unpkg.com/seqviz"></script>

<script>
  window.seqviz
    .Viewer("root", {
      name: "L09136",
      seq: "tcgcgcgtttcggtgatgacggtgaaaacctctgacacatgca",
      style: { height: "100vh", width: "100vw" }
    })
    .render();
</script>

**Comment by jjti** [comment]
It might just be me but it looks there's a space between SeqViz and the Viewer. Like ". SeqViz"

**Comment by jjti** [comment]
Let me know if that wasn't the issue
