### ISSUE TITLE
Visualising amino acid sequences

### ISSUE THREAD

**Issue by danielfoliveira1** [Lattice-Automation/seqviz#115]
Hello!
First of all, thank you for this awesome tool!
I'm using the React SeqViz component to display nucleotide sequences but I would also like to display, in the same component, my own amino acid sequences instead of the translated version provided by seqviz. I tried to input my amino acid sequence in the "seq" prop but the spacing between each AA is quite irregular and specially problematic with the I's (see attached).
I'm wondering if there is any easy fix for this... Perhaps a prop for custom AA sequences plus one to turn off the display of nucleotides or a boolean AA sequence prop that would adjust the spacing in case the input sequence is AA?

Looking forward to hearing your feedback.
Thanks,
Daniel

Note: I did change the CSS style of the component but I believe that is not what is causing the issue since nucleotides work fine.
<img width="666" alt="Screenshot 2021-10-14 at 16 38 17" src="https://user-images.githubusercontent.com/26153227/137350821-2cb695fc-ac5b-409d-b1c6-38bb22e292bf.png">

**Comment by jjti** [comment]
Hey there, right now the seq prop can, unfortunately, only be used for DNA sequences. I can see point in adding this change though and am open to both proposals re: how to add this as a prop, will investigate

**Comment by odanieloliveira** [comment]
Awesome, I appreciate that! Looking forward to hear back from you

**Comment by jjti** [comment]
Hey do you mind sharing your CSS file? I'm testing SeqViz with an AA sequence and it seems to work fine. Screenshot below:

<img width="802" alt="Screen Shot 2021-11-21 at 1 41 57 PM" src="https://user-images.githubusercontent.com/13923102/142774979-b7f8919a-b698-4dbe-88be-f08ab4dfa2b6.png">

It relies on a pretty specific monospaced font. Maybe in your CSS it was changed to something not monospace?

**Comment by jjti** [comment]
Closing because given testing ref'ed above I expect it to work fine with amino acid sequences
