### ISSUE TITLE
Single location features are displayed wrong

### ISSUE THREAD

**Issue by Midnighter** [Lattice-Automation/seqviz#117]
Hi,

I have a problem with single letter features. I thought it was a [problem with BioPython](https://github.com/biopython/biopython/issues/3766) but it seems the issue is here. A single location feature will be written as

```
     primer_bind     2150
```

Such a feature is then displayed by seqviz from that location until the end of the `source`, for example,

```
     source          1..12405
```

when it should indeed be a single letter long.

**Comment by jjti** [comment]
Looking at the BioPython issue this seems like a Genbank specific issue. I will post an adjustment fix for features like this

**Comment by jjti** [comment]
I believe this is fixed in latest patched version: `3.0.43`. Lmk if it's still an issue after updating

**Comment by Midnighter** [comment]
That did it! Thank you for the quick fix.
