### ISSUE TITLE
Change default annotation colors?

### ISSUE THREAD

**Issue by EthanHolleman** [Lattice-Automation/seqviz#120]
Hello! I was wondering if there is a way to change annotation colors for an entire viewer instance. seqViz is rendering genbank files really well but the default coloring is black features with black text making them hard to read. Thanks!

**Comment by jjti** [comment]
Do you mind sharing the genbank (or at least one that's representative?). From description it either seems like a bug, or the features have a color set to black within the genbank.

The `props.colors` array is for default colors for annotations from GenBank that don't have color set. If they're being set in the GenBank, they'll be ignored.

**Comment by jjti** [comment]
In any case, we could add a prop that overrides Genbank annotation colors. Please let me know about the example Genbank when you get a chance

**Comment by jjti** [comment]
Closing for now. For future ref: you can change the colors used by changing the colors of the annotations in the source Genbank file. It takes the annotation colors from there
