### ISSUE TITLE
'Right click' options in Sequence Viewer

### ISSUE THREAD

**Issue by elizabethmauro** [Lattice-Automation/seqviz#128]
Right click options for sequences (in sequence viewer)
Copying translations, reverse complement, ect.

**Comment by jjti** [comment]
quick comment here which is that we can expose a callback like `onContextmenu` in the top level viewer. We should not incorporate a context menu or use that event ourselves, that will break existing apps

https://developer.mozilla.org/en-US/docs/Web/API/Element/contextmenu_event

devs can technically already do context menus via `onSelection` but I can see a point for adding this in addition

**Comment by jjti** [comment]
Closing because we'll want consumers of the lib to implement the context menu themselves
