### ISSUE TITLE
Accept amino acid sequence input

### ISSUE THREAD

**Issue by elizabethmauro** [Lattice-Automation/seqviz#129]
Can display them now, but it seems like they are being treated as DNA with non-standard letters,
Might be useful for coloring. 
More notes on this request:: Seqviz isn’t meant to directly display protein sequences on their own. We used the linear display to show protein sequences, which works fine. However, there isn’t any specific functionality for protein sequences (e.g. coloring amino acids like you can with DNA).

**Comment by jjti** [comment]
proteins sequences == translations == amino acid sequences. They're all the same thing and are currently in seqviz (as ranges to translate, convert from DNA -> AA). The non-standard letters are the AAs which make up the protein seq: https://en.wikipedia.org/wiki/Protein_primary_structure

I think request/ask is to accept AA seqs as input in addition to DNA seqs -- ie skip the translation -- which is cool/worth doing. Could re-use the existing `Translation` classes/rows

**Comment by jjti** [comment]
added this in https://github.com/Lattice-Automation/seqviz/releases/tag/3.4.0

The coloring and searching and everything from DNA is supported. I'm not 100% sure this is what they wanted, exactly, but it's in there

<img width="396" alt="Screen Shot 2022-07-13 at 11 01 58 PM" src="https://user-images.githubusercontent.com/13923102/178896825-16aefe19-fdb7-4e52-a5d3-ec3074148139.png">
