### ISSUE TITLE
Scaling / Repositioning components

### ISSUE THREAD

**Issue by elizabethmauro** [Lattice-Automation/seqviz#130]
Easily rescale and position the linear and circular components relative to each other. We found a way to rescale after some trial and error. Though wondering if an easier / more flexible method could be implemented.

**Comment by jjti** [comment]
Imo this needs more context. The viewers already scale to the size of their container div (via flexbox and sizeme). Users can select to use linear and/or a circular viewer, and their position relative to one another, so a consumer of the lib already has full control over positioning and scaling
