### ISSUE TITLE
Consecutive selections of an annotation do not predictably trigger the onSelection() function.

### ISSUE THREAD

**Issue by ND56** [Lattice-Automation/seqviz#142]
**Describe the bug**

I'm not sure if this is a bug or a feature, but I noticed that---when clicking on the same annotation---the onSelection() function was not getting executed multiple times.

This poses an issue for my use of the Sequence Viewer for the following reason:

- I have state that tracks the selected annotation
- The onSelection() function I pass to the Sequence Viewer sets that state
- I have a button that clears the selected annotation that was stored in state
- So if I select an annotation -> the onSelection gets executed as expected and sets the annotation in state -> but if I then select the button to clear the selection -> then click the same annotation again -> the onSelection() function is not getting executed (so the selection is not getting set in state)
- the work around seems to be that I need to click another annotation first before again clicking the desired annotation

**Expected behavior**

- My expectation was that the onSelection() would get executed again and the annotation would get stored as the selected annotation again.

**Comment by jjti** [comment]
Fairly sure this was fixed over in https://github.com/Lattice-Automation/seqviz/pull/144
