### ISSUE TITLE
Question: Hide/show of Linear Sequence View

### ISSUE THREAD

**Issue by eoberortner** [Lattice-Automation/seqviz#153]
To be clear, this is a question and not a feature request nor bug report.

Is there a way to hide the Linear Sequence View? An example use case looks like as follows: First, the user sees only the plasmid. Then, when the user clicks a specific part, only the sequence of the part is displayed in the linear sequence view pane. 

Thanks for clarification!

**Comment by jjti** [comment]
I believe that will be possible via the `options.viewer (='both')` setting/prop. Eg if using React:

```
<SeqViz
  viewer="circular"
/>

// they click an annotation

<SeqViz
  viewer="linear"
/>
```

The state is within the component so shouldn't change

**Comment by jjti** [comment]
star the repo @eoberortner we do this for the dopamine!

**Comment by eoberortner** [comment]
awesome! this is the option I was looking for. I missed it when reading the documentation. Thanks for pointing this out!

**Comment by jjti** [comment]
Left out, but you probably saw, that you could do this within an "onSelection" callback

**Comment by eoberortner** [comment]
> Left out, but you probably saw, that you could do this within an "onSelection" callback

Thanks @jjtimmons for explicitly pointing this out!
