### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by jjti** [Lattice-Automation/seqviz#154]
- multiple starting sequence highlights showing up

<img width="513" alt="Screen Shot 2022-07-09 at 12 48 02 PM" src="https://user-images.githubusercontent.com/13923102/178117219-2b69822c-10ff-4280-851b-149681707e45.png">

- missing annotation border

<img width="238" alt="Screen Shot 2022-07-09 at 12 48 40 PM" src="https://user-images.githubusercontent.com/13923102/178117195-9a2e072e-ef71-4a00-84ca-93cfcbef4780.png">

- highlight range appears a couple pixels below centered

<img width="215" alt="Screen Shot 2022-07-09 at 12 49 57 PM" src="https://user-images.githubusercontent.com/13923102/178117236-ef6cb508-cd71-43d3-9267-5cd89b9aac39.png">

- enzyme highlight range appears also not vertically aligned

<img width="258" alt="Screen Shot 2022-07-09 at 12 50 43 PM" src="https://user-images.githubusercontent.com/13923102/178117253-5f1a5ce2-ba0b-49ba-934f-06fbf4318ae6.png">

- I can't select anything on circular viewer...

<img width="139" alt="Screen Shot 2022-07-09 at 2 19 50 PM" src="https://user-images.githubusercontent.com/13923102/178119829-83f5f678-9f41-44e8-8328-6af32e79b271.png">

- cannot select annotations on circular, are below the index

**Comment by jjtimmons** [comment]
@ninjha01 I'm seeing a number of bugs/regressions in the viewer. I'm going to go thru them quickly this afternoon to fix some of them. I think that two things will help avoid in future: better unit testing and better reviews. Unit testing JS/UI is always tedious and of questionable cost/benefit. So I'm going to ask that we do more thorough PRs in the future

**Comment by jjti** [comment]
https://github.com/Lattice-Automation/seqviz/pull/156

**Comment by jjti** [comment]
fix circular drag/select: https://github.com/Lattice-Automation/seqviz/pull/158

**Comment by jjti** [comment]
fix enzyme alignments: https://github.com/Lattice-Automation/seqviz/pull/160
