### ISSUE TITLE
Sequence annotations loaded from Benchling display in the opposite direction

### ISSUE THREAD

**Issue by amijalis** [Lattice-Automation/seqviz#166]
Hello!

When I load a file containing a sequence in Benchling's JSON format, annotations with property `strand:-1` appear as directionless, while annotations with `strand: 1` appear in the reverse direction. It's worth noting that I'm not sure of the best way to load a sequence from JSON — I currently convert the JSON to a string and create a File object out of that, which I pass into SeqViz.

Example:
<img width="276" alt="Screen Shot 2022-07-25 at 3 24 57 PM" src="https://user-images.githubusercontent.com/4912334/180858313-42dd7102-2777-4fad-9d93-9a2414f22f42.png">

<img width="196" alt="Screen Shot 2022-07-25 at 3 25 24 PM" src="https://user-images.githubusercontent.com/4912334/180858365-8195a5de-a111-4aa7-a86c-8efdf4977bcd.png">

Environment details:
 - OS: Mac OS
 - Browser: Chrome
 - Version: 3.5.4

**Comment by jjti** [comment]
Hello and thanks for reporting this! Do you mind sharing the string or file of the iGEM json. It should work as you tried. That's maybe not the recommended method, but it should work

**Comment by jjti** [comment]
re: above, I think I found/fixed the issue. Please try the latest version and let me know if you still see an issue!

Fixed + test added in https://github.com/Lattice-Automation/seqviz/commit/812ee2401bcb3aaa1883352b931ba5c25238a1fd

**Comment by amijalis** [comment]
Thanks for looking into this issue! I can't wait to try the solution. Unfortunately when using the latest version of SeqViz I get a cryptic uncaught exception error when including the SeqViz component in my app. I'll report back when I figure this out.

**Comment by jjti** [comment]
> Unfortunately when using the latest version of SeqViz I get a cryptic uncaught exception error when including the SeqViz component in my app. I'll report back when I figure this out.

Do you mind sharing? I'm not sure it's `SeqViz` related, but if it is I'd like to know/fix
