### ISSUE TITLE
Migrate to something framework agnostic

### ISSUE THREAD

**Issue by jjti** [Lattice-Automation/seqviz#178]
**Summarize your feature idea. (Why)**

From Justin at GenomeMiner:

> it would be cool if it was written in a web component exportable way (like is possible using svelte where you can compile to a web component, and maybe some other way thats possible besides svelte ??) so that it could be used in any JS project without having to use React. I moved on from React awhile ago code in Vue or Svelte primarily so in order to use seqviz I wrap it in React runtime just to use it w/ vue/svelte.

I was also kicking around Stencil: https://github.com/ionic-team/stencil

Obviously, Vue is ascendant, and Svelte too, so I can definitely see a strong argument for this if SeqViz is meant to have longevity. We provide a thin wrapper around the React implementation right now, but there are emergent frameworks that make it easy to compile across implementations

**Comment by sfc9982** [comment]
How to use it with Vue now?

**Comment by bugzpodder** [comment]
> How to use it with Vue now?

https://github.com/Lattice-Automation/seqviz#without-react

**Comment by guzmanvig** [comment]
@jjti based on https://github.com/Lattice-Automation/seqviz#without-react, this is done right?

**Comment by jjti** [comment]
not quite @guzmanvig the downside there is we're still using React to render the component, so anyone, even if using Vue, is also using React. I don't think it's a big deal tho. And moving to something framework agnostic would be a large rewrite with potential blockers along the way. Closing now
