### ISSUE TITLE
CDN folder empty

### ISSUE THREAD

**Issue by stemcell000** [Lattice-Automation/seqviz#182]
**Describe the bug**
The CDN path https://unpkg.com/seqviz leads to an empty folder. Seqwiz have stopped working for more than a week because of this.
When I use the url in my browser it ends with the following message : Cannot find "/dist/seqviz.min.js" in seqviz@3.5.26. I found out the last available version is at https://unpkg.com/seqviz@3.5.22/dist/seqviz.min.js which works when I use it as the CDN although, this must not be the last version.

**Expected behavior**

**Screenshots**

**Your environment:**

**Comment by jjti** [comment]
Fixed! Sorry about that: https://github.com/Lattice-Automation/seqviz/commit/ad444b1d199aa0d3b5360784ed38daa1c8771c84. Please let me know if you continue to see an issue, but I hope you won't

**Comment by stemcell000** [comment]
> Fixed! Sorry about that: [ad444b1](https://github.com/Lattice-Automation/seqviz/commit/ad444b1d199aa0d3b5360784ed38daa1c8771c84). Please let me know if you continue to see an issue, but I hope you won't

It works perfectly now. Thank you very much.
