### ISSUE TITLE
Restriction Enzyme Box is out of sync on Safari

### ISSUE THREAD

**Issue by sahasukanta** [Lattice-Automation/seqviz#193]
The boxes around restriction enzymes are slightly lower than expected when on Safari browser. 

![fwew](https://user-images.githubusercontent.com/67036234/222858334-72440b99-b71f-4916-aed8-9053f6feeffa.png)

**Comment by sahasukanta** [comment]
Same issue with search hit highlights
![unnamed](https://user-images.githubusercontent.com/67036234/222871631-68269787-5e2f-4b5b-9f2d-3804e0065ef2.png)

**Comment by jjti** [comment]
Thank you @sahasukanta for pointing this out. I experimented a bit on Safari and learned that it doesn't support this `alignment-baseline` SVG parameter I was using on text: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/alignment-baseline

I fixed this by removing that property ^

<img width="367" alt="Screenshot 2023-03-11 at 11 44 28 AM" src="https://user-images.githubusercontent.com/13923102/224496840-2c984b80-133b-47e4-a844-c477ef3e7d65.png">

**Comment by jjti** [comment]
This should be fixed in 3.7.8: https://github.com/Lattice-Automation/seqviz/releases/tag/3.7.8
