### ISSUE TITLE
removing last enzyme does not update UI

### ISSUE THREAD

**Issue by bugzpodder** [Lattice-Automation/seqviz#195]
If the enzymes prop changes from one item to an empty list, the UI doesn't remove the last enzyme from the viewer

last enzyme that was removed does not show up

**Screenshots**

https://codesandbox.io/s/seqviz-2034785vi2ht-forked-9tj4sv?file=/src/App.js

**Your environment:**

**Comment by jjti** [comment]
This is incredible @bugzpodder, thank you for the easily reproducible example: 

<img width="219" alt="Screenshot 2023-03-11 at 10 43 08 AM" src="https://user-images.githubusercontent.com/13923102/224493842-f6ade873-f21e-4e56-8040-38dbcfbd6231.png">

**Comment by jjti** [comment]
Should be fixed in the latest release: https://github.com/Lattice-Automation/seqviz/releases/tag/3.7.7

Example here: https://codesandbox.io/s/seqviz-2034785vi2ht-forked-brbi5v 

I'm going to close, but please lmk if you continue to have issues
