### ISSUE TITLE
out of order annotations show up in multiple rows

### ISSUE THREAD

**Issue by bugzpodder** [Lattice-Automation/seqviz#201]
**Describe the bug**

out of order annotations show up in multiple rows

**Expected behavior**

annotations show up in same row

**Screenshots**

codesandbox(https://codesandbox.io/s/seqviz-2034785vi2ht-forked-9tj4sv?file=/src/App.js)

**Your environment:**

**Comment by jjti** [comment]
Another awesome bug example @bugzpodder

**Comment by jjti** [comment]
@bugzpodder I pushed a fix for this in https://github.com/Lattice-Automation/seqviz/releases/tag/3.7.11

forked codesandbox here: https://codesandbox.io/s/seqviz-2034785vi2ht-forked-3hi419?file=/src/App.js

thank you again for the great bug report/repro, much appreciated
