### ISSUE TITLE
Unable to display protein sequence

### ISSUE THREAD

**Issue by kegelken** [Lattice-Automation/seqviz#202]
I recently noticed that, using the exact same code as before, protein sequences are not showing anymore. I am using following example code:
```
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/regenerator-runtime@0.13.3/runtime.min.js"></script>
<script type="text/javascript" src="https://unpkg.com/seqviz"></script>

<div id="seq_root"></div>

<script>
window.seqviz.Viewer("seq_root", {
        "name": "TNF_partial", 
        "seq": "mstesmirdvelaeealpkktggpqgsrrclflslfsflivagattlfcllhfgvigpqr", 
        "viewer": "linear",
        "showIndex": true,
        "style": {height: "calc(300px)", width: "100%" }, 
        "zoom": {linear: 50, circular: 10 }, "rotateOnScroll": false
}).render();
</script>  
```
Using this code, following is seen on the screen:
<img width="740" alt="Screenshot 2023-03-30 at 1 49 16 PM" src="https://user-images.githubusercontent.com/74491663/228826904-e0145ee8-9ab4-4826-9b8b-805ee582c305.png">
The sequence itself is present, can be selected and copied but the letters itself are not displayed.

Please advice on how to solve this issue.
Kind regards

**Comment by jjti** [comment]
hey @kegelken, sorry about, I think it's fixed now in the latest patch. Eg here: https://codesandbox.io/s/seqviz-2034785vi2ht-forked-9du0eg?file=/src/App.js

release of new patch here: https://github.com/Lattice-Automation/seqviz/releases/tag/3.7.12

**Comment by jjti** [comment]
@kegelken please let me know if you run into this again or more issues

**Comment by kegelken** [comment]
@jjtimmons indeed, everything is displayed as expected! Thank you so much for the quick response and fix!
