### ISSUE TITLE
Is it possible to pass in both `seq` and `compSeq`?

### ISSUE THREAD

**Issue by amijalis** [Lattice-Automation/seqviz#203]
Is it possible to define how both strands of a sequence are displayed?

Currently I only know of a way to pass in one strand of a sequence for display. I would like to represent overhangs for a particular sequence, which could look something like:

`OOOOGATC`
`CAGACTAG`

There is currently a parameter that I see in the code base called compSeq. I haven't had success passing this into SeqViz, so I'm curious how to use it. Thanks!

**Comment by jjti** [comment]
Hey @amijalis, yes this should definitely be possible. Sorry for this issue. It should be fixed, now, in 3.7.13: https://github.com/Lattice-Automation/seqviz/releases/tag/3.7.13

Example here: https://codesandbox.io/s/seqviz-2034785vi2ht-forked-0x4bsp?file=/src/App.js

**Comment by jjti** [comment]
Please let me know if you run into any more issues or this continues to be an issue

**Comment by amijalis** [comment]
Works perfectly for me now! Thank you!!
