### ISSUE TITLE
Write-features for Seqviz

### ISSUE THREAD

**Issue by isaacguerreir** [Lattice-Automation/seqviz#224]
Right now I would like to know if would it be possible to write sequences by writing manually the base pairs, or by pasting the sequence on the view?

**Comment by bugzpodder** [comment]
Hello @isaacguerreir you can store the debounced user input in a useState (or in case of paste, listen to a paste clipboardevent) and then pass this value as props to SeqViz

**Comment by isaacguerreir** [comment]
Is it possible to have access to the information about where the cursor is on the sequence viewer regarding the position? (so it would be possible to paste a subsequence on parts of the sequence).

**Comment by bugzpodder** [comment]
sure, just use controlled state selection/onSelection: https://github.com/Lattice-Automation/seqviz/#selection-

**Comment by leshane** [comment]
@isaacguerreir - Do you have enough information now to trigger an edit sequence component on user input / paste? 

@jjti - My sense is that the UI/UX for editing a sequence, that can be triggered by user input, should *not* be built into SeqViz. In other words, SeqViz will provide the handlers but it won't be opinionated about the UI implementation for sequence editing. Hopefully that makes sense. Thoughts?

**Comment by jjti** [comment]
> @jjti - My sense is that the UI/UX for editing a sequence, that can be triggered by user input, should _not_ be built into SeqViz. In other words, SeqViz will provide the handlers but it won't be opinionated about the UI implementation for sequence editing. Hopefully that makes sense. Thoughts?

Yeah I agree w/ that and the suggestion that bugzpodder provided with:
> sure, just use controlled state selection/onSelection: https://github.com/Lattice-Automation/seqviz/#selection-

I'll close for now but re-open if I'm missing something @isaacguerreir, or you think that using the existing props is insufficient for seq editing
