### ISSUE TITLE
Introduce a Primer element

### ISSUE THREAD

**Issue by leshane** [Lattice-Automation/seqviz#232]
## Summary of the feature idea
Introduce a "primer" element. Primers are short nucleic acid sequences that play a role in PCR reactions. For users, being able to create and view primers will facilitate planning PCR reactions and plasmid assemblies.

## Details

- Introduce a primer element, distinct from yet similar to an annotation.
- Users should be able to interact with a primer
- Users should be able to set the start and end index of the primer, the DNA sequence, the orientation (forward or reverse), and color.

## Example primer visualization

<img width="421" alt="Screenshot 2023-09-16 at 4 30 53 PM" src="https://github.com/Lattice-Automation/seqviz/assets/3424830/412134bf-f0b7-4e8a-ba0c-389dd55e5ab6">

**Comment by isaacguerreir** [comment]
Hey everyone, 

I made PR #242 for the primer element. Would like to start a conversation now that I have an understanding of Seqviz 'under the hood', and ask your opinions about how primers should be visualized.

- How it's the design so far? Would like some changes on the SVG?
- Would you prefer to have a name or the sequence on the primer component?'
- Would you prefer to be transparent or color-filled?
- Would you prefer to have one line for each primer direction as I made so far or do you prefer both primer directions on the same line?
- Would you like to have a primer component on the circular view also?

![image](https://github.com/Lattice-Automation/seqviz/assets/19381976/460e7bed-2aa7-4484-9349-1017dd757ead)

**Comment by isaacguerreir** [comment]
By looking at the `PrimerProps` params, it seems they follow the same structure as annotations. One problem not covered with this abstraction is when synthetic biologists want to design degenerate primers. A PCR primer sequence is called degenerate if some of its positions have several possible bases. Degenerate primers use an extended alphabet to represent their combinatorial degeneracy:
```
    N   Any nucleotide
    A   Adenine
    G   Guanine
    C   Cytosine
    T   Thymine
    R   Purine (A or G)
    Y   Pyrimidine (C or T)
    W   Weak (A or T)
    S   Strong (G or C)
    M   Amino (A or C)
    K   Keto (G or T)
    B   Not A (G or C or T)
    H   Not G (A or C or T)
    D   Not C (A or G or T)
    V   Not T (A or G or C)
```

I don't know if it will be important to cover this aspect of the primer design (and possibly visualization against a target sequence), but I'm sharing so we have this information ahead of time.

**Comment by isaacguerreir** [comment]
Hey @leshane. Do you think the merged PR #242 is enough to close this issue or should we wait for the circular component to do it?

**Comment by isaacguerreir** [comment]
Can we close it?

**Comment by guzmanvig** [comment]
@isaacguerreir and @leshane , I'm gonna go ahead and close the issue. If a circular view is needed for Primers, we can create an issue for that specifically. The same happens for the Translation handles and IIRC Kevin told me it was okay to show it only in the linear view
