### ISSUE TITLE
Add a Translation handle element

### ISSUE THREAD

**Issue by leshane** [Lattice-Automation/seqviz#233]
## Summary of the feature idea
A way to name and select an entire translation. Currently, it's only possible to select individual amino acid elements in the sequence viewer. It's possible to create/select an annotation that covers the same sequence as a translation, but the two are not connected in any way. 

The idea is to make a connected, full-length translation handle so the user can select an entire translation and optionally name and color the translation.

## Example of a translation element

<img width="821" alt="Screenshot 2023-09-16 at 5 27 36 PM" src="https://github.com/Lattice-Automation/seqviz/assets/3424830/06f34ce7-153d-4ec8-ad4f-f59000caee8f">

**Comment by guzmanvig** [comment]
@jjti I've been looking into this issue. I have 2 approaches and wanted to know your opinion:

1 - Modify the `TranslationRow` component so in addition to draw multiple `SingleNamedElement` for the aminoacids it also draws a new `TranslationHandle` component for the entire row.  i.e.:

```
const TranslationRow = (props: {
  bpsPerBlock: number;
  charWidth: number;
  findXAndWidth: FindXAndWidthType;
  firstBase: number;
  fullSeq: string;
  height: number;
  inputRef: InputRefFunc;
  lastBase: number;
  onUnmount: (a: unknown) => void;
  seqType: SeqType;
  translations: Translation[];
  y: number;
}) => (
  <>
    {props.translations.map((t, i) => (
      <SingleNamedElement
        {...props} // include overflowLeft in the key to avoid two split annotations in the same row from sharing a key
        key={`translation-linear-${t.id}-${i}-${props.firstBase}-${props.lastBase}`}
        translation={t}
      />
    ))}
    <TranslationHandle
        {...props}
        {etc}
      />
  </>
);
```


The problem with this approach is that now the `TranslationRow` has to occupy kind of double the height, and that breaks the whole logic of the `translationYDiff` and `elementHeight`,

2 - The other approach is to create another element similar to `TranslationRows`, like `TranslationHandleRows` and add it in the same way that the translations are added, i.e.:

```
{translationRows.length && (
          <TranslationRows
            bpsPerBlock={bpsPerBlock}
            charWidth={charWidth}
            elementHeight={elementHeight}
            findXAndWidth={this.findXAndWidth}
            firstBase={firstBase}
            fullSeq={fullSeq}
            inputRef={inputRef}
            lastBase={lastBase}
            seqType={seqType}
            translationRows={translationRows}
            yDiff={translationYDiff}
            onUnmount={onUnmount}
          />
        )}
{translationHandleRows.length && (
          <TranslationHandleRows
            translationHandleRows={translationHandleRows}
           {etc}
          />
        )}
...
```

The advantage is that the `translationYDiff` and `elementHeight` logic still applies. The downside is that it seems to me that we would be creating a separate component for translations when there's already one.
    
I may be missing something. Let me know what you think!

**Comment by guzmanvig** [comment]
Completed in PR #254
