### ISSUE TITLE
How to turn off "translation" for amino acid seqs?

### ISSUE THREAD

**Issue by rtviii** [Lattice-Automation/seqviz#274]
I unfortunately get this "translation" annotation at the bottom of the sequence, which i don't see how i would ve enabled. 

It's pretty annoying because i can't select ranges of residues (the moment you clikc on one the whole sequence gets selected via this blue `translation` flyer). I was looking forward to using the 'linear' version of the viz...

Just installed the packaged and tried the simple example:
```typescript
import { SeqViz } from "seqviz"
...
  <SeqViz
    name="J23100"
    seq="MEQYYGTGRRKEAVARVFLRPGNGKVTVNGQDFNEYFQGLVRAVAALEPLRAVDALGRFDAYITVRGGGKSGQIDAIKLGIARALVQYNPDYRAKLKPLGFLTRDARVVERKKYGKHKARRAPQYSKR"
    // annotations={[{ name: "promoter", start: 0, end: 34, direction: 1, color: "blue" }]}
  />
```

![image](https://github.com/user-attachments/assets/9f52da35-e797-437e-b309-32492dcab759)

**Comment by guzmanvig** [comment]
Thanks for reporting this. You are correct, this is indeed a bug. Will be fixed soon.
