### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by JJTimmons** [Lattice-Automation/seqviz#33]
**Is your feature request related to a problem? Please describe.**
Translations are absent from SeqViz. Are a way to visualize translated amino acid sequences. Should be exposed via something similar to the annotations schema.

**Describe the solution you'd like**
- [ ] Be able to programmatically specify a translated region through a "translations" property on input
- [ ] Be able to infer which open reading frames are large enough to automatically have translations shown (with a programmatically exposed default parameter)

**Describe alternatives you've considered**
Only ambiguity here is around:

1. automatic inference open reading frames that should be translated (based on length, or length as a ratio of full sequence, or whether the sequence is just a single ORF)?
2. whether we also want an ORF toggle. I put ORFs (different from translations) in Loom but that wasn't ported over either

**Additional context**
I already made this in Loom's sequence viewer, see screenshot below, but it wasn't copied over when parts of that viewer were made open-source.

![Screen Shot 2019-10-22 at 11 06 05 AM](https://user-images.githubusercontent.com/13923102/67300710-652d3000-f4bc-11e9-9627-cc9028a7c9f6.png)

**Comment by haasleah** [comment]
This looks great, thanks!

**Comment by JJTimmons** [comment]
hey @haasleah, checkout the translations property used for input and let me know if that's alright. An alternative would be to have like a `translationThreshold` property where the sequence is scanned for ORFs and translated if they meet or exceed that value, rather then manual method here
