### ISSUE TITLE
Add color-coded bp

### ISSUE THREAD

**Issue by JJTimmons** [Lattice-Automation/seqviz#35]
**Describe the feature you'd like added**
Nucleotides should be color-codable for differentiation.

**(Optional) Describe examples of similar features elsewhere**
Benchling's circular viewer _almost_ has this but not quite since the bp are shown are rectangles when zoomed in enough.

![Screen Shot 2019-10-22 at 11 30 07 AM](https://user-images.githubusercontent.com/13923102/67302945-abd05980-f4bf-11e9-9af1-7784c469821b.png)

**Additional context**
Will likely be added as a key-value object through input. Example below. Undefined colorings will remain black.

An alternative or secondary approach would be to have bpColors accept a boolean, and use the "colors" already passed for annotations to seed the bp colors.

```js
{
    ...restOfOptions,
    bpColors: {
        A: "#ff0000",
        T: "#00ff00",
        G: "#ffa500",
        C: "#ffff00",
    }
}
```

**Comment by haasleah** [comment]
This looks great, thanks!

**Comment by JJTimmons** [comment]
closed by https://github.com/Lattice-Automation/seqviz/commit/765d29e61b6e098ace6cda7391d2d584fcf5a00b

**Comment by JJTimmons** [comment]
```js
  bpColors: {
    a: "#FF0000",
    t: "#00ff00"
  },
```

creates

![Screen Shot 2019-11-07 at 4 46 34 PM](https://user-images.githubusercontent.com/13923102/68431633-b60d7b80-0180-11ea-93c6-e0f9fe7523ff.png)
