### ISSUE TITLE
Changing bpColors does not immediately re-render

### ISSUE THREAD

**Issue by haasleah** [Lattice-Automation/seqviz#44]
**Describe the bug**
When toggling bpColors on and off, the colors do not appear until you scroll down to view parts of the sequence that are not currently visible.

**To Reproduce**
- Create a toggle to turn bpColors on and off
- When toggling, see the colors don't immediately change

**Expected behavior**
The colors should immediately change when toggling bpColors on and off

**Screenshots**
<img width="1343" alt="Screen Shot 2019-12-04 at 10 55 37 AM" src="https://user-images.githubusercontent.com/45974914/70158405-2e366680-1685-11ea-8a44-7b3077f73d81.png">

**Desktop (please complete the following information):**

- OS: iOS
- Browser: Chrome
- Version: 78

**Comment by JJTimmons** [comment]
This should also be fixed now. Please let me know either way. In addition, I added the method below to the Viewer for updating properties without having to make a new viewer and re-render in multiple steps:

<img width="523" alt="Screen Shot 2019-12-06 at 9 28 15 AM" src="https://user-images.githubusercontent.com/13923102/70330092-d6c20300-180a-11ea-978e-86997a1ebc4d.png">

**Comment by haasleah** [comment]
I updated to version 0.6.3 and I'm now getting an error: `TypeError: console.warning is not a function`. 

If I only update to version 0.6.0 though the colors are now working as expected!

Please let me know if you'd like me to submit another ticket for the above error or if you need more information.

**Comment by JJTimmons** [comment]
Oops. Removed in 0.6.4. Sorry about that. After this next round of input/API changes I'll try to expand testing to catch some of these.
