### ISSUE TITLE
Annotation extends too far with short sequences

### ISSUE THREAD

**Issue by haasleah** [Lattice-Automation/seqviz#55]
**Describe the bug**
For sequences that have a length shorter than the first row, the annotation extends past the end of the sequence to the end of the row.

**To Reproduce**
Using part: 
![Screen Shot 2019-12-06 at 2 33 43 PM](https://user-images.githubusercontent.com/45974914/70350783-71cfd280-1835-11ea-86db-45a4bc102dad.png)

Results in:
<img width="1319" alt="Screen Shot 2019-12-06 at 2 34 24 PM" src="https://user-images.githubusercontent.com/45974914/70350820-857b3900-1835-11ea-951f-32436b72b18c.png">

**Expected behavior**
I expect the annotation to only extend to the length of the sequence.

**Comment by JJTimmons** [comment]
Was able to replicate:

![Screen Shot 2019-12-09 at 4 08 40 PM](https://user-images.githubusercontent.com/13923102/70479749-09d6f180-1aac-11ea-9259-1e9d32e06323.png)

I believe that it's fixed now:
![Screen Shot 2019-12-09 at 4 22 05 PM](https://user-images.githubusercontent.com/13923102/70479763-0f343c00-1aac-11ea-976b-6051def94152.png)
