### ISSUE TITLE
Viewer cut short within some containers

### ISSUE THREAD

**Issue by JJTimmons** [Lattice-Automation/seqviz#59]
**Describe the bug**
Viewer is being cut short: not all SeqBlocks are being rendered

**To Reproduce**
Wrap in another div that doesn't fill vertical space of the viewer?

**Additional context**
![unnamed](https://user-images.githubusercontent.com/13923102/70551217-18251c00-1b45-11ea-99ab-c31fba563403.png)

**Comment by haasleah** [comment]
To be clear, if I continue scrolling the rest of the sequence will appear. It just doesn't seem to render immediately.

**Comment by JJTimmons** [comment]
Can created something similar with a wrapper div with 200px of padding. I don't think the InfiniteScroll is calc'ing the viewer's actual distance from the div's top right. Hope it's the same issue.

![Screen Shot 2019-12-11 at 4 39 10 PM](https://user-images.githubusercontent.com/13923102/70662732-d96e8f00-1c34-11ea-880e-f28eef7a7b9e.png)

**Comment by JJTimmons** [comment]
I believe that this is fixed in v1.0.3.

![Screen Shot 2019-12-11 at 5 03 25 PM](https://user-images.githubusercontent.com/13923102/70664305-29028a00-1c38-11ea-9bf6-06bd40e6dc0f.png)

Needed to account for the parent component's distance from top:

![Screen Shot 2019-12-11 at 5 00 04 PM](https://user-images.githubusercontent.com/13923102/70664147-d628d280-1c37-11ea-8ac9-7a735787bb39.png)
