### ISSUE TITLE
Sidebar enzyme selection TypeError bug

### ISSUE THREAD

**Issue by leshane** [Lattice-Automation/seqviz#69]
The error below was produced by opening SeqViz in Chrome (v. 79.0.3945.88), loading the default part K1598008, and click-selecting any of the enzymes in the sidebar. 

`react-dom.production.min.js:5940 Uncaught TypeError: e is not a function`
`at t.exports (seqviz.min.js:56)`
`at t.exports (seqviz.min.js:18)`
`at seqviz.min.js:56`
`at seqviz.min.js:56`
`at Array.reduce (<anonymous>)`
`at seqviz.min.js:56`
`at t.value (seqviz.min.js:56)`
`at Pi (react-dom.production.min.js:3785)`
`at Si (react-dom.production.min.js:3776)`
`at Ii (react-dom.production.min.js:3960)`

**Comment by JJTimmons** [comment]
fixed in https://github.com/Lattice-Automation/seqviz/commit/88b581ede41d540ee637609bc6e3271c055a8148
