### ISSUE TITLE
demo in vanilla js

### ISSUE THREAD

**Issue by m1-bioinfo-amu-01** [Lattice-Automation/seqviz#81]
Hi,
 I'm trying to redo the show meta from demo but in vanilla js im encourtering some trouble to do so because the tutorial is made for react. Could it be possible to do the demo in vanilla js ?

**Comment by jjti** [comment]
checkout https://github.com/Lattice-Automation/seqviz/blob/develop/src/index.js and the index.html file next to it, both are in just plain JS
