### ISSUE TITLE
NCBI Accession ID query fails

### ISSUE THREAD

**Issue by azhx** [Lattice-Automation/seqviz#83]
Hi, I wanted to test your `options.accession` feature where you say you are able to populate annotations for any given NCBI accession ID. I ran the demo on my machine via `npm start` and tried to search an NCBI accession ID, but it logged a CORS error. I tried to add a `"proxy":"https://localhost:3001"` but still couldn't get it to work.

The ID I tested was `34577062` 
And the error was 

```
Access to fetch at 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nuccore&id=34577062&rettype=gbwithparts&retmode=text' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field x-requested-with is not allowed by Access-Control-Allow-Headers in preflight response.
```

Am I missing something basic?

**Comment by jjti** [comment]
Apologies for that. I replicated your issue and believe I fixed. Checkout the latest version: 3.0.26
