### ISSUE TITLE
Genbank annotation parsing

### ISSUE THREAD

**Issue by mlincoln-achelois** [Lattice-Automation/seqviz#84]
Hi! I was running into some trouble with annotations when giving the SeqViz component a Genbank file to read. The visualization appears correctly, but none of the annotations have the proper name parsed from the Genbank file, instead labeled as something like "CDS-648".

After doing some digging in `io/parsers/genbank.js`, I think I've found the cause of the issue. On line 189 of `io/parsers/genbank.js`, new annotations are given the default name `${type}-${start}`, however this introduces a bug later on. In line 211 of `io/parsers/genbank.js`, as part of the defensive check to see if a name isn't already defined for the annotation, it checks if `annotations[annotations.length - 1].name === "Untitled"`. This will never be true, since the default name given is something like "CDS-648", so none of the annotations ever get a proper name set.

I propose that either the default name given is "Untitled" on line 189 of `io/parsers/genbank.js`, or the condition `annotations[annotations.length - 1].name === "Untitled"` on line 211 of `io/parsers/genbank.js` is removed.

Thanks!

**Comment by jjti** [comment]
Hey! Sorry this is super late. A colleague has submitted a CR that I believe fixes this issue: https://github.com/Lattice-Automation/seqviz/pull/85/files. I'll let you know after a patch is live

**Comment by jjti** [comment]
try the latest version when you get a chance and let me know if issues persist (or don't). I made a change on top of Zach's change to try and fix the annotation naming weirdness
