### ISSUE TITLE
How to load map from file?

### ISSUE THREAD

**Issue by nicolazilio** [Lattice-Automation/seqviz#86]
Hello there,

I have been trying to load a plasmid map in either GenBank or SnapGene format with the code below without success (= white page). The issue is that I don't get any errors, so I am not sure what the problem is. I have also tried to substitute map_blob for map_file for the file option, again no luck. 

Any ideas?

Thank you very much in advance.

```
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script type="text/javascript"
        src="https://cdn.jsdelivr.net/npm/regenerator-runtime@0.13.3/runtime.min.js"></script>
    <script type="text/javascript" src="https://unpkg.com/seqviz"></script>
</head>

<body>
    <div id="root"></div>
    <script>
        
        var map_blob = new XMLHttpRequest();
        map_blob.open("GET", "https://urltofile.com/my_file.gbk");
        map_blob.responseType = "blob";
        map_blob.send();
        
        var map_file = new File([map_blob.response], "test_file");

        window.seqviz
            .Viewer("root", {
                file: map_blob.response,
                style: { height: "100vh", width: "100vw" }
            })
            .render();
    </script>
</body>

</html>
```

**Comment by jjti** [comment]
Assuming that the import and file and all that works (looks like it does, w/o trying to relocate), my guess is that it's because SeqViz tries to size to fit the HTML Element that it's rendered within. I'm not certain but that might be it.

Can you try again but render within a div with a hard coded height/width?

**Comment by nicolazilio** [comment]
I don't think that's the reason. If a replace `file: map_blob.response ` with `name: "L09136", seq: "TGCAGGTCGACTCTAGAGGATCC"`, I get a nice map. I tried to encapsulate the <script> element within a div with hard coded sizes, but that didn't work either. 

I think that the blob is fine. Running `map_blob.response` returns
`Blob {size: 23575, type: "application/octet-stream"}`, and running `map_blob.response.text()` returns
```
Promise {<pending>}__proto__: Promise[[PromiseState]]: "fulfilled"[[PromiseResult]]: "LOCUS       Exported               11995 bp ds-DNA     circular SYN 23-APR-2020
↵DEFINITION  synthetic circular DNA
↵ACCESSION   .
↵VERSION     .
↵KEYWORDS    .
[additional content in here]
↵"
```

**Comment by jjti** [comment]
hey sorry for huge delay. I tried the below to try and replicate, but am still failing to do so. The result from the below is what I'd expect, where the viewer renders fine.

Sorry to pry, but do you have a URL I could request the genbank from to test this?

```js
/**
 * This module is only used for developing seqviz
 * See viewer.js for the library's entrypoint
 */
import { Viewer } from "./viewer";

import fetch, { Request } from "node-fetch";


(async () => {
  let file = await fetch(new Request("./io/examples/genbank/NC_011521.gb", { headers: { "X-Requested-With": "XMLHttpRequest" } }))
  .then(response => response.text())
  .catch(console.error);

  file = new File([file], "NC_011521")
  console.log(file)

  const viewerInput = {
    // name: "L09136",
    // seq: "tcgcgcgtttcggtgatgacggtgaaaacctctgacacatgca",
    viewer: "both",
    // accession: "NC_011521",
    file: file,
    // backbone: "pSB1C3",
    showAnnotations: true,
    showPrimers: true,
    showComplement: true,
    showIndex: true,
    zoom: { linear: 50 },
    colors: [],
    onSearch: results => {
      console.log("Your Search Results: ", results);
    },
    search: { query: "gtacc" },
    enzymes: ["EcoRI"],
    copyEvent: event => event.key === "c" && (event.metaKey || event.ctrlKey),
    style: { height: "calc(100vh - 20px)", width: "calc(100vw)" }
  };
  
  // let viewer = window.seqviz.Viewer("app-root", viewerInput);
  let viewer = Viewer("root", viewerInput);
  viewer.render();
})();
```

**Comment by jjti** [comment]
Gonna close in a few days. Still down to try and replicate/fix if there's an issue, but IIRC I could not

**Comment by jjti** [comment]
Closing for now because I couldn't replicate. Please re-open if this remains and issue and I'll try to fix
