### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by Mokey2002** [Lattice-Automation/seqviz#89]
Hi, 
Is there a way to load the demo using CDN and not npm

**Comment by jjti** [comment]
Like hypothetically or as an example of how to do it? Hypothetically, yes. Our demo has a bunch of other UI pieces, and we like React, so it's in React, but anyone could implement the demo page in raw JS or with some other framework, as well.

Let me know if this is unclear or I can help some other way

https://github.com/Lattice-Automation/seqviz/blob/develop/demo/src/index.jsx
