### ISSUE TITLE
position-specific color feature

### ISSUE THREAD

**Issue by Sanrrone** [Lattice-Automation/seqviz#91]
Dears,
Thanks for this friendly tool to visualize sequences. I read the manual and I notice is possible to change the nucleotides colors, but this apply to the whole sequence. Is there a way to set up for a specific position?

for example: ```bpColors: { 10: "#FF0000", 11: "#00FFFF" }```
meaning nucleotide position instead the nucleotide itself.

thanks in advance!

**Comment by jjti** [comment]
Ok I just pushed a change with this in `3.0.28`. Screenshot below. Heads up that they're 0-based, not 1-based.

```
  bpColors: {
    10: "green",
    200: "blue",
    201: "red"
  },
```

<img width="683" alt="Screen Shot 2021-02-15 at 8 08 37 PM" src="https://user-images.githubusercontent.com/13923102/108006590-e372e700-6fc9-11eb-8f1d-c2144fd5738d.png">
