### ISSUE TITLE
Add annotation names to tooltip on hover of split annotations

### ISSUE THREAD

**Issue by Sanrrone** [Lattice-Automation/seqviz#93]
Dears,
I made two annotations with same lengths and same text length inside. but one of them is not showed because of the split in the sequence (image below):
![Captura de pantalla de 2021-03-01 16-31-33](https://user-images.githubusercontent.com/15197238/109548775-d6ff8b80-7aab-11eb-8fc9-b2b73460bfcb.png)
in circular representation the annotation is ok but not in linear.
 I reproduce this with the following minimal example:

```
<script>
  window.seqviz
    .Viewer("root", {

      seq: "TTATGTATGGCGTTGTCCTTGGAGTATTAATATTGTTCATGTGGGCAGGCTCAGGTTTATGTATGGCGTTGTCCTTGGAGTATTAATATTGTTCATGTGGGCAGGCTCAGGT",
      annotations: [
        {start: 50, end: 70, name: "test2 with long text inside", direction: 1},
        {start: 75, end: 95, name: "test2 with long text inside", direction: 1}
      ],
      style: { height: "100vh", width: "90vw" },
    })
    .render();
</script>
```
it is really a bug?, could the text be split as same the annotation tag?.

thanks in advance!
Sandro

**Comment by jjti** [comment]
That was on purpose, since the text would be cut-off anyway during the line-break. I don't really have a solution for that one. We could maybe add a tooltip popover to show the annotation, but it still wouldn't be visible unless the user hovered

**Comment by Sanrrone** [comment]
a tooltip popover is a good choice, and if that were customizable in the annotation tag would be even better.

**Comment by jjti** [comment]
Okay I added this bit as a feature. I'll take some more time than the other things, so I can't get a good ETA right this second

**Comment by jjti** [comment]
Also please star the repo. I'm maintaining this for the ~dopamine~ Github stars
