### ISSUE TITLE
Annotation names from Genbank file priorize genes names.

### ISSUE THREAD

**Issue by Sanrrone** [Lattice-Automation/seqviz#97]
Hello again!,
I think I found another bug. when I read a .gb file, seqviz uses the "label" tag inside the gb to label the annotation name tag, but, in my gb I have a label and gene tag (both and one in some elements). When I load the file seqviz uses the gene tag to label the graph instead so I cannot visualize what I want. 
I created a minimal example to reproduce this behaviour.
```
<input type=file id=file onchange="onChange(event)">
<div id="root"></div>
<script type="text/javascript" src="https://unpkg.com/babel-regenerator-runtime@6.5.0/runtime.js"></script>
<script src="https://unpkg.com/seqviz"></script>
<script>
  function onChange(event) {
  var fileinput = event.target.files[0];
  var reader = new FileReader();

  window.seqviz.Viewer("root", {
    file: fileinput,
    style: { height: "100vh", width: "90vw" },
  }).render();
}
</script>
```
in my example, I have two elements in the gb file, `ori` and `CmR`. The last also have gene tag called `cat` which is what I see after run the example, but I want to see the labels tag in all cases.
![Captura de pantalla de 2021-03-09 11-56-34](https://user-images.githubusercontent.com/15197238/110492089-a1245d80-80d0-11eb-92a3-40f24ec07614.png)

I attatech my gb if you want to reproduce it as well.
[test.zip](https://github.com/Lattice-Automation/seqviz/files/6109446/test.zip)

is this a bug? or seqviz priorize some tags than label?

thanks in advance!
Best,
Sandro

**Comment by jjti** [comment]
Right now SeqViz will take the first Genbank tag that's within a set (below). There's no precedence so one is prioritized above the others, it's just whichever tag comes first in the Genbank. I'm not sure that our current behavior is right, to be honest:

```
// a list of recognized types that would constitute an annotation name
const tagNameSet = new Set(["gene", "product", "note", "db_xref", "protein_id", "label", "lab_host", "locus_tag"]);

// a list of tags that could represent colors
const tagColorSet = new Set(["ApEinfo_fwdcolor", "ApEinfo_revcolor", "loom_color"]);
```

**Comment by Sanrrone** [comment]
To be honest as well, I don't know what would be the best behaviour but I think this could be a new feature to keep all the annotations in the same line. But I can live without it hahaha.

thanks!
