### ISSUE TITLE
Annotation name not returned from setSelection

### ISSUE THREAD

**Issue by crudnicky** [Lattice-Automation/seqviz#99]
Hello! First - thanks for building such a great tool! I'm having a lot of fun building an application around it. I have come across a small bug when clicking on a plasmid annotation. The seqviz docs explain that the object emitted following an annotation click should look like this:

`{
  // selection
  "name": ...
  "type": ... 
  "seq": ... 
  "gc": ... 
  "tm": ... 
  "start": ...
  "end": ... 
  "length": ...
  "direction": ...
  "clockwise": ...
  "color": ...
}`

however object I am capturing looks like this:

`{
clockwise: ...
element: ...
end: ...
gc: ...
length: ...
ref: ...
seq: ...
start: ...
tm: ...
type: ...
}`

I am creating my seqviz annotation objects with this shape:

`const seqVizAnnotation = {
            id: qualifiers.standard_name + makeId(1),
            start: location.intervals[0].start,
            end: location.intervals[0].end,
            direction: translateDirection(feature.strand),
            name: qualifiers.standard_name,
            color: translateColors(feature.type),
            type: feature.type
          }`

I noticed that in SeqViz repo file `src/utils/sequence.js>annotationFactory:221` that the id and color property have default values, however if I remove the id and color property from the `seqVizAnnotation` object I pass to the viewer, the viewer will not render ids, colors, or proper keys on the rendered elements. If I include the id and color, then that value is mapped to the "ref" and the viewer is fixed, but I am unable to capture the name of an annotation when I click on it. In order to hack my way around these issues I am using the id property in the `seqVizAnnotation` object for the UID of each annotation and as the "name" for an annotation that has been clicked on. 

I believe that refactoring `setSelection` in `src/SeqViz/handlers/selection.jsx:354-375` could alter the object that is actually emitted when an annotation is clicked on to match what the docs say I should be returning.

**Comment by jjti** [comment]
Hello there! Thanks for checking out SeqViz and deep-diving this particular issue

I recently made a fix that I believe addresses this bug: https://github.com/Lattice-Automation/seqviz/issues/96 (just a few days ago). Fix would've been in v3.0.34.

This is the diff: https://github.com/Lattice-Automation/seqviz/commit/c1c3fa1462eadd2a94c7cc9db506d0948134e809

Please try again w/ the latest version and letting me know if the issue persists

**Comment by crudnicky** [comment]
@JJTimmons Updating did the trick! Thanks for pointing that out. I'll be more mindful about looking out for future updates!
